config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :tasks, only: :show
    end
  end

  resources :tasks, only: [:new, :create, :edit, :update] do
    collection do
      post :sync
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  skip_before_action :authenticate
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::BaseController
  def show
    values = Fetcher::Task.by_uuid(params[:id])
    render status: :ok, json: values.to_hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  USERS = { 'task' => 'warrior' }.freeze

  before_action :authenticate

  def authenticate
    return unless Rails.env.production?
      authenticate_or_request_with_http_digest do |username|
        USERS[username]
      end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Fetcher::Task.pending_tasks(params)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task_form = TaskForm.new(TaskFormValues.new)
  end

  def create
    @task_form = TaskForm.new(TaskFormValues.new, params)

    Creator::Task.new(@task_form.model).invoke

    redirect_to root_path
  end

  def edit
    values = Fetcher::Task.by_uuid(params[:id])
    form_values = TaskFormValues.new(values.to_hash.slice(:uuid, :description, :next_action, :website, :project))
    @task_form = TaskForm.new(form_values)
  end

  def update
    values = Fetcher::Task.by_uuid(params[:id])
    form_values = TaskFormValues.new(values.to_hash.slice(:uuid, :description, :next_action, :website, :project))
    task_form = TaskForm.new(form_values, params)

    Updater::Task.new(values).with_form_values(task_form.model)

    redirect_to root_path
  end

  def sync
    Syncer::Tasks.invoke

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.row
  .col-xs-12
    h1 Pending tasks
    = link_to('Reset filters', root_path)
.row
  .col-xs-12
    table.table.table-striped.table-condensed#tasks
      thead
        th Description
        th Next action
        th Tags
        th Website
        th Project
      tbody
        - @tasks.each do |task|
          tr[data-uuid=task.uuid]
            td[data-toggle="modal" data-target="#task_detail"]= task.description
            td= task.next_action
            td
              - if task.tags
                == task.tags.join('<br />')
            td= link_to(task.website, root_path(website: task.website))
            td= link_to(task.project, root_path(project: task.project))

= link_to('Sync', sync_tasks_path, class: 'btn btn-primary', method: :post)

.modal.fade.in#task_detail[aria-labelledby="myLargeModalLabel" role="dialog"]
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close[aria-label="Close" data-dismiss="modal" type="button"]
          span[aria-hidden="true"] ×
        h4.modal-title Task Details
      .modal-body
        .row
          .col-xs-12
            .col-xs-8
              dl.dl-horizontal
                dt Next action
                dd.next_action
                dt Mailtext
                dd.mail_body

              strong Annotations
              ul.list-group#annotations

              = link_to 'Edit task', '#', class: 'btn btn-primary', id: 'edit-task'

            .col-xs-4
              .row
                .cols-xs-12
                  .well
                    dl.dl-horizontal#task_meta
                      dt Created
                      dd.created
                      dt Website
                      dd.website
                      dt Project
                      dd.project
              .row
                .cols-xs-12
                  .panel.panel-primary
                    .panel-heading Tags
                    .panel-body#tags

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='nl'>
  <head> <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <title>TaskWarrior</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">TaskWarrior</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class='active'>
            <%= link_to('Home', '#') %>
            </li>
            <li>
            <%= link_to('Pending', '#') %>
            </li>
          </ul>
          <p class="navbar-text navbar-right">
            <%= link_to 'Add task', new_task_path, class: 'navbar-link' %>
          </p>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.slim
.form-group
  = f.label :description
  = f.text_field :description, class: 'form-control'
.form-group
  = f.label :next_action
  = f.text_field :next_action, class: 'form-control'
.form-group
  = f.label :website
  = f.text_field :website, class: 'form-control'
.form-group
  = f.label :project
  = f.text_field :project, class: 'form-control'
= f.submit 'Submit', class: 'btn btn-primary'

app/views/tasks/edit.html.slim
.row
  .col-12-xs
    = form_for(@task_form, method: :put, url: task_path(@task_form.model.uuid)) do |f|
      = render partial: 'form', locals: {f: f}

app/views/tasks/new.html.slim
.row
  .col-12-xs
    = form_for(@task_form) do |f|
      = render partial: 'form', locals: {f: f}